name: Workflow develop

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  increment_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Increment SNAPSHOT VERSION on develop push
      - name: Increment SNAPSHOT version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
          IFS='.' read -ra ADDR <<< "$BASE_VERSION"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))-SNAPSHOT"
          mvn versions:set -DnewVersion=$NEW_VERSION
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "Increment SNAPSHOT version to $NEW_VERSION"
          git push origin develop

  # Build the project after increment_version or release_version
  build:
    runs-on: ubuntu-latest
    needs: increment_snapshot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test -Dparallel=none

      - name: Package the application
        run: mvn package -DskipTests

  # Analyse SonarQube only for pushes on develop branch
  sonarqube:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=Torrents-Uploader-Web \
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
          -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }} \
          -Dsonar.java.binaries=target