name: Develop Branch Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test -Dparallel=none

      - name: Package the application
        run: mvn package -DskipTests

  # Analyse SonarQube only for pushes on develop branch
  sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=Torrents-Uploader-Web \
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
          -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }} \
          -Dsonar.java.binaries=target