name: Release Workflow

on:
  workflow_run:
    workflows: [ "Workflow master" ]
    types:
      - completed

jobs:
  release_version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: 'release-branch-**'
          fetch-depth: 0

      - name: Display current branch and files
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "Files in working directory:"
          ls -al

      - name: Check if version files exist
        run: |
          if [ -f .release_version ]; then
            echo ".release_version file exists"
          else
            echo ".release_version file does not exist"
            exit 1
          fi
          if [ -f .release_dev_version ]; then
            echo ".release_dev_version file exists"
          else
            echo ".release_dev_version file does not exist"
            exit 1
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Read Version Info
        id: read_version
        run: |
          NEW_VERSION=$(cat .release_version)
          NEW_DEV_VERSION=$(cat .release_dev_version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_dev_version=$NEW_DEV_VERSION" >> $GITHUB_ENV

      - name: Perform release
        run: |
          mvn --batch-mode release:prepare release:perform -DreleaseVersion=${{ env.new_version }} -DdevelopmentVersion=${{ env.new_dev_version }}
          git push origin HEAD --tags

      # maybe increment snapshot on develop branch ?


#  docker:
#    runs-on: ubuntu-latest
#    needs: release_version
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#
#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
#
#      - name: Build Docker image
#        run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest
#
#      - name: Push Docker image
#        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-spring-boot-app:latest